---
players:
  mpv:
    name: mpv
    executable: mpv
    fullscreen: "--fs"
    pip: "--ontop --no-border --autofit=384x216 --geometry=98\\%:98\\% "
    enqueue: ""
    new_window: ""
    needs_ipc: true
    flag_overrides: {}
