# vim:ft=toml
{{- if (or (eq .profile "minimal") (eq .profile "full")) }}
[".config/mpv/scripts/mpvSockets.lua"]
    type = "file"
    url = "https://raw.githubusercontent.com/wis/mpvSockets/master/mpvSockets.lua"
    refreshPeriod = "168h"
[".local/src/dwmf"]
    type = "git-repo"
    url = "https://github.com/romariorobby/dwmf.git"
    refreshPeriod = "168h"
[".config/emacs-doom"]
	args = "--depth 1"
	type = "git-repo"
	url = "https://github.com/doomemacs/doomemacs"
    refreshPeriod = "168h"
[".emacs.d"]
    type = "git-repo"
    url = "https://github.com/plexus/chemacs2"
    refreshPeriod = "168h"
{{- end }}
[".local/src/PKGBUILDs"]
    type = "git-repo"
    url = "https://github.com/romariorobby/PKGBUILDs.git"
    refreshPeriod = "168h"
