#+TITLE: Programs
#+AUTHOR: Romario
#+OPTIONS: toc:nil

#+begin_quote
*NOTE:* Currently Only supported Debian/Ubuntu and Arch Linux Distribution.
#+end_quote

* Naming Conventions
** Profile

#+TBLNAME: Profile
uses these with chezmoi for spesifically what packages to be installed.
| SERVER | BASE | MINIMAL | FULL |
|--------+------+---------+------|
| S      | B    | M       | F    |

- *NOTE*: If there's 'X' on PROFILE there will be ignored.

*** SERVER/HEADLESS
*** BASE
*** MINIMAL
*** FULL
** Tag

#+TBLNAME: TAG
| MAIN | AUR | PIP | NPM | GIT |
|------+-----+-----+-----+-----|
| M    | A   | P   | N   | G   |

- *NOTE*: If there's 'X' on tag there will be ignored.
- *NOTE*: If there's suffix 'P' on tag AUR(A) it means installed on personal PKGBUILDS.
*** MAIN
installing packages through main package manager such as ~pacman~, ~apt~.
*** AUR
installing packaages through aur such as on Arch Linux (~paru~, ~yay~), although there some AUR-Like on ubuntu like [[https://github.com/pacstall/pacstall][pacstall]].
TODO: installation script AUR? for ubuntu/debian
**** Installing using Pacstall (Ubuntu/Debian User)
- Add Pacstall custom sources
#+begin_src shell
pacstall -A "https://github.com/romariorobby/aer-pacstall-program"
#+end_src
**** Installing using makedeb (Ubuntu/Debian User)
     TODO: Makedeb
*** PIP
    pip
*** NPM
    npm
*** GIT
    ?
** Packages
*** Emacs

you need ~emacs-28~ to work properly with [[https://github.com/doomemacs/doomemacs/][doom-emacs]]
**** Note for Ubuntu/Debian

#+begin_src shell
sudo add-apt-repository ppa:kelleyk/emacs
sudo apt install emacs28
# Remove
# sudo apt autoremove --purge emacs28
# sudo add-apt-repository --remove ppa:kelleyk/emacs
#+end_src

see this for more https://github.com/kelleyk/ppa-emacs

*** Siji Font
**** font not detected by ~fc-list~
    try remove ~/etc/fonts/conf.d/70-no-bitmaps~
    then update again with ~fc-cache~

** Description
Its self-explanatory. it should concise what packages does.
